name: Release
on:
  push:
    branches:
      - 'main'
  pull_request: {}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel ongoing builds
        uses: styfle/cancel-workflow-action@0.9.0

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: 🚀
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17
          branch: main
          extra_plugins: |
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
